import test from 'node:test';
import assert from 'node:assert/strict';
import { ACTIONS, applyAction, createInitialState, getLegalCards, isLegalPlay, restoreState, serializeState } from '../dist/game-engine/engine.js';
import { COLORS, TYPES, createDeck, createDeckSet, makeCard } from '../dist/game-engine/cards.js';
import { cardHTML } from '../dist/ui/card.js';
import { calculateRoundScore, createQuickSession, createTavernMatch, finishRound, restoreSession, serializeSession, standings, startNextRound } from '../dist/game-engine/match.js';

let seq=0; const c=(type,color='wild',value=null)=>makeCard(type,color,value,`t${++seq}`);
function state({hands=[[c(TYPES.NUMBER,'red',3)],[c(TYPES.NUMBER,'blue',4)]],top=c(TYPES.NUMBER,'red',5),activeColor=top.color,players=hands.length}={}){
  return {version:4,seed:7,phase:'playing',players:Array.from({length:players},(_,i)=>({id:`p${i}`,name:`P${i}`,kind:i?'ai':'human',hand:hands[i]||[]})),drawPile:Array.from({length:40},(_,i)=>c(TYPES.NUMBER,COLORS[i%4],(i%9)+1)),discardPile:[top],effectiveTopIndex:0,currentPlayerIndex:0,direction:1,activeColor,activePenalty:null,taki:null,freePlay:false,mustPlayAgain:false,awaitingColor:null,candidateWinnerId:null,winnerId:null,turn:1,log:[]};
}
const play=(s,p,card)=>applyAction(s,{type:ACTIONS.PLAY,playerId:p,cardId:card.id});

test('game deck has the complete 120-card Elder composition',()=>{assert.equal(createDeckSet().length,60);assert.equal(createDeck().length,120);assert.equal(createDeck().filter(x=>x.type===TYPES.NUMBER).length,72);assert.equal(createDeck().filter(x=>x.type===TYPES.PLUS2).length,8)});
test('deals eight to 2–10 players',()=>{for(const n of [2,4,10]){const s=createInitialState({playerCount:n,seed:2});assert.equal(s.players.length,n);assert.ok(s.players.every(p=>p.hand.length===8))}});
test('opening card is always a regular number',()=>{for(let seed=1;seed<=80;seed++)assert.equal(createInitialState({playerCount:4,seed}).discardPile[0].type,TYPES.NUMBER)});
test('legal color match',()=>{const card=c(TYPES.NUMBER,'red',2),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]});assert.equal(isLegalPlay(s,'p0',card.id),true)});
test('legal type/value match',()=>{const card=c(TYPES.NUMBER,'blue',5),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]});assert.equal(isLegalPlay(s,'p0',card.id),true)});
test('illegal card rejected',()=>{const card=c(TYPES.NUMBER,'blue',2),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]});assert.equal(isLegalPlay(s,'p0',card.id),false);assert.throws(()=>play(s,'p0',card))});
test('drawing exactly one ends turn so card cannot be immediately played',()=>{const s=state(),n=s.players[0].hand.length,x=applyAction(s,{type:ACTIONS.DRAW,playerId:'p0'});assert.equal(x.players[0].hand.length,n+1);assert.equal(x.currentPlayerIndex,1);assert.equal(getLegalCards(x,'p0').length,0)});
test('Stop skips the next player',()=>{const card=c(TYPES.STOP,'red'),s=state({players:3,hands:[[card],[c(TYPES.NUMBER,'blue',4)],[c(TYPES.NUMBER,'green',4)]]});assert.equal(play(s,'p0',card).currentPlayerIndex,2)});
test('Reverse changes direction with 3 players',()=>{const card=c(TYPES.REVERSE,'red'),s=state({players:3,hands:[[card,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'blue',4)],[c(TYPES.NUMBER,'green',4)]]}),x=play(s,'p0',card);assert.equal(x.direction,-1);assert.equal(x.currentPlayerIndex,2)});
test('Reverse is a quiet ordinary card with 2 players',()=>{const card=c(TYPES.REVERSE,'red'),s=state({hands:[[card,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'blue',4)]]}),x=play(s,'p0',card);assert.equal(x.direction,1);assert.equal(x.currentPlayerIndex,1);assert.equal(x.log.some(entry=>entry.type==='reverse'),false)});
test('Plus grants another turn',()=>{const card=c(TYPES.PLUS,'red'),s=state({hands:[[card,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'blue',4)]]}),x=play(s,'p0',card);assert.equal(x.currentPlayerIndex,0);assert.equal(x.mustPlayAgain,true)});
test('Plus as last card does not win and forces a draw',()=>{const card=c(TYPES.PLUS,'red'),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]}),x=play(s,'p0',card);assert.equal(x.phase,'playing');assert.equal(x.mustPlayAgain,true);const y=applyAction(x,{type:ACTIONS.END_TURN,playerId:'p0'});assert.equal(y.players[0].hand.length,1)});
test('stacked +2 accumulates and resolves before the last-card player wins',()=>{const a=c(TYPES.PLUS2,'red'),b=c(TYPES.PLUS2,'blue'),s=state({players:3,hands:[[a,c(TYPES.NUMBER,'red',1)],[b],[c(TYPES.NUMBER,'green',4)]]});let x=play(s,'p0',a);x=play(x,'p1',b);assert.equal(x.activePenalty.amount,4);const before=x.players[2].hand.length;x=applyAction(x,{type:ACTIONS.DRAW,playerId:'p2'});assert.equal(x.players[2].hand.length,before+4);assert.equal(x.winnerId,'p1');assert.equal(x.activePenalty,null)});
test('Change Color waits for and applies choice',()=>{const card=c(TYPES.CHANGE_COLOR),s=state({hands:[[card,c(TYPES.NUMBER,'blue',2)],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',card);assert.ok(x.awaitingColor);x=applyAction(x,{type:ACTIONS.CHOOSE_COLOR,playerId:'p0',color:'green'});assert.equal(x.activeColor,'green');assert.equal(x.currentPlayerIndex,1)});
test('TAKI sequence defers intermediate commands and closes automatically',()=>{const taki=c(TYPES.TAKI,'red'),plus=c(TYPES.PLUS,'red'),num=c(TYPES.NUMBER,'red',7),s=state({hands:[[taki,plus,num,c(TYPES.NUMBER,'blue',9)],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',taki);x=play(x,'p0',plus);x=play(x,'p0',num);assert.equal(x.taki,null);assert.equal(x.mustPlayAgain,false);assert.equal(x.currentPlayerIndex,1);assert.ok(x.log.some(e=>e.type==='takiClosed'))});
test('a different-colored TAKI cannot be played inside an open TAKI',()=>{const redTaki=c(TYPES.TAKI,'red'),blueTaki=c(TYPES.TAKI,'blue'),redCard=c(TYPES.NUMBER,'red',2),s=state({hands:[[redTaki,blueTaki,redCard],[c(TYPES.NUMBER,'red',8)]]});const x=play(s,'p0',redTaki);assert.equal(isLegalPlay(x,'p0',blueTaki.id),false);assert.equal(isLegalPlay(x,'p0',redCard.id),true)});
test('fresh TAKI never carries into the next player turn',()=>{const redTaki=c(TYPES.TAKI,'red'),blueCard=c(TYPES.NUMBER,'blue',2),s=state({hands:[[redTaki,blueCard],[c(TYPES.NUMBER,'red',8)]]});const x=play(s,'p0',redTaki);assert.equal(x.currentPlayerIndex,1);assert.equal(x.taki,null)});
test('player can end an active TAKI and it closes automatically',()=>{const taki=c(TYPES.TAKI,'red'),a=c(TYPES.NUMBER,'red',2),b=c(TYPES.NUMBER,'red',4),s=state({hands:[[taki,a,b],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',taki);x=play(x,'p0',a);x=applyAction(x,{type:ACTIONS.END_TURN,playerId:'p0'});assert.equal(x.taki,null);assert.equal(x.currentPlayerIndex,1)});
test('Super TAKI inherits current color in rules and rendering',()=>{const superTaki=c(TYPES.SUPER_TAKI),s=state({hands:[[superTaki,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'blue',4)]]});const x=play(s,'p0',superTaki);const played=x.discardPile.at(-1);assert.equal(x.taki.color,'red');assert.equal(x.activeColor,'red');assert.equal(played.inheritedColor,'red');assert.match(cardHTML(played),/card red type-superTaki inherited/)});
test('King cancels +2 and creates a free extra turn',()=>{const king=c(TYPES.KING),s=state({hands:[[king,c(TYPES.NUMBER,'blue',2)],[c(TYPES.NUMBER,'blue',4)]]});s.activePenalty={kind:'plus2',amount:6};const x=play(s,'p0',king);assert.equal(x.activePenalty,null);assert.equal(x.freePlay,true);assert.equal(x.currentPlayerIndex,0);assert.equal(getLegalCards(x,'p0').length,1)});
test('King may win as final card',()=>{const king=c(TYPES.KING),s=state({hands:[[king],[c(TYPES.NUMBER,'blue',4)]]});const x=play(s,'p0',king);assert.equal(x.phase,'finished');assert.equal(x.winnerId,'p0')});
test('reaching one card is acknowledged automatically without a penalty',()=>{const a=c(TYPES.NUMBER,'red',2),b=c(TYPES.NUMBER,'red',4),opp=c(TYPES.NUMBER,'blue',2),s=state({hands:[[a,b],[opp,c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',a),before=x.players[0].hand.length;assert.ok(x.log.some(e=>e.type==='lastCard'&&e.playerId==='p0'));x=play(x,'p1',opp);assert.equal(x.players[0].hand.length,before)});
test('ordinary final card wins',()=>{const card=c(TYPES.NUMBER,'red',2),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]});const x=play(s,'p0',card);assert.equal(x.phase,'finished');assert.equal(x.winnerId,'p0')});
test('draw pile reshuffles discarded cards without losing the top',()=>{const s=state();s.drawPile=[];s.discardPile=[c(TYPES.NUMBER,'blue',1),c(TYPES.NUMBER,'green',2),c(TYPES.NUMBER,'red',5)];s.effectiveTopIndex=2;const x=applyAction(s,{type:ACTIONS.DRAW,playerId:'p0'});assert.equal(x.players[0].hand.length,2);assert.ok(x.discardPile.some(k=>k.color==='red'))});
test('state serialization restores the exact match',()=>{const s=createInitialState({playerCount:4,seed:99});assert.deepEqual(restoreState(serializeState(s)),s)});
test('Tavern Match initializes exactly four players and five rounds',()=>{const m=createTavernMatch({seed:12});assert.equal(m.mode,'tavern');assert.equal(m.totalRounds,5);assert.equal(m.round,1);assert.equal(m.game.players.length,4);assert.deepEqual(Object.values(m.scores),[0,0,0,0])});
test('round score is the sum of all losing hands',()=>{const m=createTavernMatch({seed:4});m.game.phase='finished';m.game.winnerId='p0';m.game.players.forEach((p,i)=>p.hand=Array(i?i+1:0).fill(c(TYPES.NUMBER,'red',1)));assert.equal(calculateRoundScore(m.game),9);const done=finishRound(m);assert.equal(done.scores.p0,9);assert.equal(done.results[0].points,9)});
test('AI and human winners receive cumulative scores',()=>{let m=createTavernMatch({seed:4});m.game.phase='finished';m.game.winnerId='p1';m.game.players.forEach((p,i)=>p.hand=Array(i===1?0:2).fill(c(TYPES.NUMBER,'red',1)));m=finishRound(m);assert.equal(m.scores.p1,6);m=startNextRound(m);m.game.phase='finished';m.game.winnerId='p0';m.game.players.forEach((p,i)=>p.hand=Array(i?1:0).fill(c(TYPES.NUMBER,'blue',2)));m=finishRound(m);assert.equal(m.scores.p0,3);assert.equal(m.scores.p1,6)});
test('five normal rounds produce final standings',()=>{let m=createTavernMatch({seed:9});for(let round=1;round<=5;round++){m.game.phase='finished';m.game.winnerId='p0';m.game.players.forEach((p,i)=>p.hand=Array(i?1:0).fill(c(TYPES.NUMBER,'red',1)));m=finishRound(m);if(round<5)m=startNextRound(m);}assert.equal(m.phase,'matchFinished');assert.equal(m.championId,'p0');assert.equal(m.results.length,5);assert.equal(standings(m)[0].id,'p0')});
test('tied final standings trigger sudden death and its winner is champion',()=>{let m=createTavernMatch({seed:11});m.round=5;m.scores={p0:10,p1:10,p2:3,p3:2};m.game.phase='finished';m.game.winnerId='p2';m.game.players.forEach(p=>p.hand=[]);m=finishRound(m);assert.equal(m.suddenDeath,true);assert.equal(m.phase,'betweenRounds');m=startNextRound(m);assert.equal(m.round,5);assert.equal(m.game.players.length,4);m.game.phase='finished';m.game.winnerId='p1';m=finishRound(m);assert.equal(m.phase,'matchFinished');assert.equal(m.championId,'p1')});
test('Quick Play is independent from Tavern Match scoring',()=>{const q=createQuickSession({playerCount:2,seed:7});assert.equal(q.game.players.length,2);q.game.phase='finished';q.game.winnerId='p0';const done=finishRound(q);assert.equal(done.phase,'matchFinished');assert.deepEqual(done.scores,{})});
test('Tavern Match persists exactly between rounds',()=>{let m=createTavernMatch({seed:42});m.game.phase='finished';m.game.winnerId='p3';m.game.players.forEach((p,i)=>p.hand=Array(i===3?0:i+1).fill(c(TYPES.NUMBER,'green',3)));m=finishRound(m);assert.deepEqual(restoreSession(serializeSession(m)),m)});
