import test from 'node:test';
import assert from 'node:assert/strict';
import { ACTIONS, applyAction, createInitialState, getLegalCards, isLegalPlay, restoreState, serializeState } from '../dist/game-engine/engine.js';
import { COLORS, TYPES, createDeck, createDeckSet, makeCard } from '../dist/game-engine/cards.js';

let seq=0; const c=(type,color='wild',value=null)=>makeCard(type,color,value,`t${++seq}`);
function state({hands=[[c(TYPES.NUMBER,'red',3)],[c(TYPES.NUMBER,'blue',4)]],top=c(TYPES.NUMBER,'red',5),activeColor=top.color,players=hands.length}={}){
  return {version:1,seed:7,phase:'playing',players:Array.from({length:players},(_,i)=>({id:`p${i}`,name:`P${i}`,kind:i?'ai':'human',hand:hands[i]||[],declaredLastCard:false})),drawPile:Array.from({length:40},(_,i)=>c(TYPES.NUMBER,COLORS[i%4],(i%9)+1)),discardPile:[top],effectiveTopIndex:0,currentPlayerIndex:0,direction:1,activeColor,activePenalty:null,taki:null,freePlay:false,mustPlayAgain:false,awaitingColor:null,pendingReaction:null,lastCardWindow:null,candidateWinnerId:null,winnerId:null,turn:1,log:[]};
}
const play=(s,p,card)=>applyAction(s,{type:ACTIONS.PLAY,playerId:p,cardId:card.id});

test('official deck is two identical 58-card sets',()=>{assert.equal(createDeckSet().length,58);assert.equal(createDeck().length,116);assert.equal(createDeck().filter(x=>x.type===TYPES.NUMBER).length,72)});
test('deals eight to 2–10 players',()=>{for(const n of [2,4,10]){const s=createInitialState({playerCount:n,seed:2});assert.equal(s.players.length,n);assert.ok(s.players.every(p=>p.hand.length===8))}});
test('legal color match',()=>{const card=c(TYPES.NUMBER,'red',2),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]});assert.equal(isLegalPlay(s,'p0',card.id),true)});
test('legal type/value match',()=>{const card=c(TYPES.NUMBER,'blue',5),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]});assert.equal(isLegalPlay(s,'p0',card.id),true)});
test('illegal card rejected',()=>{const card=c(TYPES.NUMBER,'blue',2),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]});assert.equal(isLegalPlay(s,'p0',card.id),false);assert.throws(()=>play(s,'p0',card))});
test('drawing exactly one ends turn so card cannot be immediately played',()=>{const s=state(),n=s.players[0].hand.length,x=applyAction(s,{type:ACTIONS.DRAW,playerId:'p0'});assert.equal(x.players[0].hand.length,n+1);assert.equal(x.currentPlayerIndex,1);assert.equal(getLegalCards(x,'p0').length,0)});
test('Stop skips the next player',()=>{const card=c(TYPES.STOP,'red'),s=state({players:3,hands:[[card],[c(TYPES.NUMBER,'blue',4)],[c(TYPES.NUMBER,'green',4)]]});assert.equal(play(s,'p0',card).currentPlayerIndex,2)});
test('Reverse changes direction with 3 players',()=>{const card=c(TYPES.REVERSE,'red'),s=state({players:3,hands:[[card,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'blue',4)],[c(TYPES.NUMBER,'green',4)]]}),x=play(s,'p0',card);assert.equal(x.direction,-1);assert.equal(x.currentPlayerIndex,2)});
test('Reverse is neutral with 2 players',()=>{const card=c(TYPES.REVERSE,'red'),s=state({hands:[[card,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'blue',4)]]}),x=play(s,'p0',card);assert.equal(x.direction,1);assert.equal(x.currentPlayerIndex,1)});
test('Plus grants another turn',()=>{const card=c(TYPES.PLUS,'red'),s=state({hands:[[card,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'blue',4)]]}),x=play(s,'p0',card);assert.equal(x.currentPlayerIndex,0);assert.equal(x.mustPlayAgain,true)});
test('Plus as last card does not win and forces a draw',()=>{const card=c(TYPES.PLUS,'red'),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]}),x=play(s,'p0',card);assert.equal(x.phase,'playing');assert.equal(x.mustPlayAgain,true);const y=applyAction(x,{type:ACTIONS.END_TURN,playerId:'p0'});assert.equal(y.players[0].hand.length,1)});
test('stacked +2 accumulates and resolves before the last-card player wins',()=>{const a=c(TYPES.PLUS2,'red'),b=c(TYPES.PLUS2,'blue'),s=state({players:3,hands:[[a,c(TYPES.NUMBER,'red',1)],[b],[c(TYPES.NUMBER,'green',4)]]});let x=play(s,'p0',a);x=play(x,'p1',b);assert.equal(x.activePenalty.amount,4);const before=x.players[2].hand.length;x=applyAction(x,{type:ACTIONS.DRAW,playerId:'p2'});assert.equal(x.players[2].hand.length,before+4);assert.equal(x.winnerId,'p1');assert.equal(x.activePenalty,null)});
test('Change Color waits for and applies choice',()=>{const card=c(TYPES.CHANGE_COLOR),s=state({hands:[[card,c(TYPES.NUMBER,'blue',2)],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',card);assert.ok(x.awaitingColor);x=applyAction(x,{type:ACTIONS.CHOOSE_COLOR,playerId:'p0',color:'green'});assert.equal(x.activeColor,'green');assert.equal(x.currentPlayerIndex,1)});
test('TAKI sequence defers intermediate commands',()=>{const taki=c(TYPES.TAKI,'red'),plus=c(TYPES.PLUS,'red'),num=c(TYPES.NUMBER,'red',7),s=state({hands:[[taki,plus,num,c(TYPES.NUMBER,'blue',9)],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',taki);x=play(x,'p0',plus);x=play(x,'p0',num);x=applyAction(x,{type:ACTIONS.CLOSE_TAKI,playerId:'p0'});assert.equal(x.mustPlayAgain,false);assert.equal(x.currentPlayerIndex,1)});
test('open TAKI carries into next player turn',()=>{const taki=c(TYPES.TAKI,'red'),s=state({hands:[[taki,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'red',8)]]});let x=play(s,'p0',taki);x=applyAction(x,{type:ACTIONS.END_TURN,playerId:'p0'});assert.equal(x.taki.open,true);assert.equal(x.currentPlayerIndex,1);assert.equal(getLegalCards(x,'p1').length,1)});
test('closing TAKI clears explicit open state',()=>{const taki=c(TYPES.TAKI,'red'),num=c(TYPES.NUMBER,'red',2),s=state({hands:[[taki,num],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',taki);x=play(x,'p0',num);x=applyAction(x,{type:ACTIONS.CLOSE_TAKI,playerId:'p0'});assert.equal(x.taki,null)});
test('Super TAKI inherits current color',()=>{const superTaki=c(TYPES.SUPER_TAKI),s=state({hands:[[superTaki,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'blue',4)]]});const x=play(s,'p0',superTaki);assert.equal(x.taki.color,'red');assert.equal(x.activeColor,'red')});
test('King cancels +2 and creates a free extra turn',()=>{const king=c(TYPES.KING),s=state({hands:[[king,c(TYPES.NUMBER,'blue',2)],[c(TYPES.NUMBER,'blue',4)]]});s.activePenalty={kind:'plus2',amount:6};const x=play(s,'p0',king);assert.equal(x.activePenalty,null);assert.equal(x.freePlay,true);assert.equal(x.currentPlayerIndex,0);assert.equal(getLegalCards(x,'p0').length,1)});
test('King may win as final card',()=>{const king=c(TYPES.KING),s=state({hands:[[king],[c(TYPES.NUMBER,'blue',4)]]});const x=play(s,'p0',king);assert.equal(x.phase,'finished');assert.equal(x.winnerId,'p0')});
test('+3 hits every other player and preserves effective leading card',()=>{const plus3=c(TYPES.PLUS3),under=c(TYPES.NUMBER,'green',6),s=state({players:3,top:under,hands:[[plus3,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'blue',4)],[c(TYPES.NUMBER,'yellow',4)]]});let x=play(s,'p0',plus3);const a=x.players[1].hand.length,b=x.players[2].hand.length;x=applyAction(x,{type:ACTIONS.RESOLVE_REACTION});assert.equal(x.players[1].hand.length,a+3);assert.equal(x.players[2].hand.length,b+3);assert.equal(x.discardPile[x.effectiveTopIndex].id,under.id)});
test('+3 over active +2 joins the active penalty',()=>{const plus3=c(TYPES.PLUS3),s=state({hands:[[plus3,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'blue',4)]]});s.activePenalty={kind:'plus2',amount:4};let x=play(s,'p0',plus3);x=applyAction(x,{type:ACTIONS.RESOLVE_REACTION});assert.equal(x.activePenalty.amount,7)});
test('Broken +3 reacts outside normal turn and sends penalty back',()=>{const plus3=c(TYPES.PLUS3),broken=c(TYPES.BROKEN3),s=state({players:3,hands:[[plus3,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'blue',4)],[broken,c(TYPES.NUMBER,'green',4)]]});let x=play(s,'p0',plus3),before=x.players[0].hand.length;x=applyAction(x,{type:ACTIONS.RESPOND_BROKEN3,playerId:'p2',cardId:broken.id});assert.equal(x.players[0].hand.length,before+3);assert.equal(x.players[2].hand.some(k=>k.id===broken.id),false)});
test('the +3 player may immediately pair their own Broken +3',()=>{const plus3=c(TYPES.PLUS3),broken=c(TYPES.BROKEN3),s=state({hands:[[plus3,broken],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',plus3);x=applyAction(x,{type:ACTIONS.RESPOND_BROKEN3,playerId:'p0',cardId:broken.id});assert.equal(x.players[0].hand.length,0);assert.equal(x.winnerId,'p0')});
test('voluntary Broken +3 costs its player three cards',()=>{const broken=c(TYPES.BROKEN3),s=state({hands:[[broken,c(TYPES.NUMBER,'red',2)],[c(TYPES.NUMBER,'blue',4)]]});const before=s.players[0].hand.length,x=play(s,'p0',broken);assert.equal(x.players[0].hand.length,before-1+3)});
test('last-card declaration closes the penalty window',()=>{const a=c(TYPES.NUMBER,'red',2),b=c(TYPES.NUMBER,'red',4),s=state({hands:[[a,b],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',a);x=applyAction(x,{type:ACTIONS.DECLARE_LAST,playerId:'p0'});assert.equal(x.lastCardWindow.declared,true)});
test('missing last-card declaration draws four when next player acts',()=>{const a=c(TYPES.NUMBER,'red',2),b=c(TYPES.NUMBER,'red',4),opp=c(TYPES.NUMBER,'blue',2),s=state({hands:[[a,b],[opp,c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',a),before=x.players[0].hand.length;x=play(x,'p1',opp);assert.equal(x.players[0].hand.length,before+4)});
test('ordinary final card wins',()=>{const card=c(TYPES.NUMBER,'red',2),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]});const x=play(s,'p0',card);assert.equal(x.phase,'finished');assert.equal(x.winnerId,'p0')});
test('draw pile reshuffles discarded cards without losing the top',()=>{const s=state();s.drawPile=[];s.discardPile=[c(TYPES.NUMBER,'blue',1),c(TYPES.NUMBER,'green',2),c(TYPES.NUMBER,'red',5)];s.effectiveTopIndex=2;const x=applyAction(s,{type:ACTIONS.DRAW,playerId:'p0'});assert.equal(x.players[0].hand.length,2);assert.ok(x.discardPile.some(k=>k.color==='red'))});
test('state serialization restores the exact match',()=>{const s=createInitialState({playerCount:4,seed:99});assert.deepEqual(restoreState(serializeState(s)),s)});
