import test from 'node:test';
import assert from 'node:assert/strict';
import { ACTIONS, applyAction, createInitialState, getLegalCards, isLegalPlay, restoreState, serializeState } from '../dist/game-engine/engine.js';
import { COLORS, TYPES, createDeck, createDeckSet, makeCard } from '../dist/game-engine/cards.js';
import { cardHTML } from '../dist/ui/card.js';
import { calculateRoundScore, createDuelSession, createQuickSession, createTavernMatch, finishRound, restoreSession, roundLeader, serializeSession, standings, startNextRound } from '../dist/game-engine/match.js';
import { DUEL_OPPONENTS, getDuelOpponent } from '../dist/duel/opponents.js';
import { triggerHaptic } from '../dist/platform/storage.js';

let seq=0; const c=(type,color='wild',value=null)=>makeCard(type,color,value,`t${++seq}`);
function state({hands=[[c(TYPES.NUMBER,'red',3)],[c(TYPES.NUMBER,'blue',4)]],top=c(TYPES.NUMBER,'red',5),activeColor=top.color,players=hands.length}={}){
  return {version:4,seed:7,phase:'playing',players:Array.from({length:players},(_,i)=>({id:`p${i}`,name:`P${i}`,kind:i?'ai':'human',hand:hands[i]||[]})),drawPile:Array.from({length:40},(_,i)=>c(TYPES.NUMBER,COLORS[i%4],[1,3,4,5,6,7,8,9][i%8])),discardPile:[top],effectiveTopIndex:0,currentPlayerIndex:0,direction:1,activeColor,activePenalty:null,taki:null,freePlay:false,mustPlayAgain:false,awaitingColor:null,candidateWinnerId:null,winnerId:null,turn:1,log:[]};
}
const play=(s,p,card)=>applyAction(s,{type:ACTIONS.PLAY,playerId:p,cardId:card.id});

test('deck removes ordinary twos while retaining +2 cards',()=>{assert.equal(createDeckSet().length,56);assert.equal(createDeck().length,112);assert.equal(createDeck().filter(x=>x.type===TYPES.NUMBER).length,64);assert.equal(createDeck().filter(x=>x.type===TYPES.NUMBER&&x.value===2).length,0);assert.throws(()=>makeCard(TYPES.NUMBER,'red',2),/not part of RUNES/);assert.equal(createDeck().filter(x=>x.type===TYPES.PLUS2).length,8)});
test('unsupported or denied haptics never interrupt a game action',()=>{assert.equal(triggerHaptic('play',true,null),false);assert.equal(triggerHaptic('play',true,{vibrate(){throw new Error('unsupported')}}),false);let pattern;assert.equal(triggerHaptic('play',true,{vibrate(value){pattern=value;return true;}}),true);assert.deepEqual(pattern,[7]);});
test('deals eight to 2–10 players',()=>{for(const n of [2,4,10]){const s=createInitialState({playerCount:n,seed:2});assert.equal(s.players.length,n);assert.ok(s.players.every(p=>p.hand.length===8))}});
test('opening card is always a regular number',()=>{for(let seed=1;seed<=80;seed++)assert.equal(createInitialState({playerCount:4,seed}).discardPile[0].type,TYPES.NUMBER)});
test('legal color match',()=>{const card=c(TYPES.NUMBER,'red',3),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]});assert.equal(isLegalPlay(s,'p0',card.id),true)});
test('legal type/value match',()=>{const card=c(TYPES.NUMBER,'blue',5),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]});assert.equal(isLegalPlay(s,'p0',card.id),true)});
test('illegal card rejected',()=>{const card=c(TYPES.NUMBER,'blue',3),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]});assert.equal(isLegalPlay(s,'p0',card.id),false);assert.throws(()=>play(s,'p0',card))});
test('drawing exactly one ends turn so card cannot be immediately played',()=>{const s=state(),n=s.players[0].hand.length,x=applyAction(s,{type:ACTIONS.DRAW,playerId:'p0'});assert.equal(x.players[0].hand.length,n+1);assert.equal(x.currentPlayerIndex,1);assert.equal(getLegalCards(x,'p0').length,0)});
test('Stop skips the next player',()=>{const card=c(TYPES.STOP,'red'),s=state({players:3,hands:[[card],[c(TYPES.NUMBER,'blue',4)],[c(TYPES.NUMBER,'green',4)]]});assert.equal(play(s,'p0',card).currentPlayerIndex,2)});
test('Reverse changes direction with 3 players',()=>{const card=c(TYPES.REVERSE,'red'),s=state({players:3,hands:[[card,c(TYPES.NUMBER,'red',3)],[c(TYPES.NUMBER,'blue',4)],[c(TYPES.NUMBER,'green',4)]]}),x=play(s,'p0',card);assert.equal(x.direction,-1);assert.equal(x.currentPlayerIndex,2)});
test('Reverse is a quiet ordinary card with 2 players',()=>{const card=c(TYPES.REVERSE,'red'),s=state({hands:[[card,c(TYPES.NUMBER,'red',3)],[c(TYPES.NUMBER,'blue',4)]]}),x=play(s,'p0',card);assert.equal(x.direction,1);assert.equal(x.currentPlayerIndex,1);assert.equal(x.log.some(entry=>entry.type==='reverse'),false)});
test('Plus grants another turn',()=>{const card=c(TYPES.PLUS,'red'),s=state({hands:[[card,c(TYPES.NUMBER,'red',3)],[c(TYPES.NUMBER,'blue',4)]]}),x=play(s,'p0',card);assert.equal(x.currentPlayerIndex,0);assert.equal(x.mustPlayAgain,true)});
test('Plus follow-up still has to match color or symbol',()=>{const plus=c(TYPES.PLUS,'blue'),blue=c(TYPES.NUMBER,'blue',3),green=c(TYPES.NUMBER,'green',1),s=state({hands:[[plus,blue,green],[c(TYPES.NUMBER,'red',4)]],activeColor:'blue'});const x=play(s,'p0',plus);assert.equal(isLegalPlay(x,'p0',blue.id),true);assert.equal(isLegalPlay(x,'p0',green.id),false)});
test('King free play is consumed before a Plus follow-up',()=>{const king=c(TYPES.KING),plus=c(TYPES.PLUS,'blue'),blue=c(TYPES.NUMBER,'blue',3),green=c(TYPES.NUMBER,'green',1),s=state({hands:[[king,plus,blue,green],[c(TYPES.NUMBER,'red',4)]]});let x=play(s,'p0',king);x=play(x,'p0',plus);assert.equal(x.freePlay,false);assert.equal(x.mustPlayAgain,true);assert.equal(isLegalPlay(x,'p0',blue.id),true);assert.equal(isLegalPlay(x,'p0',green.id),false)});
test('Plus as last card does not win and forces a draw',()=>{const card=c(TYPES.PLUS,'red'),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]}),x=play(s,'p0',card);assert.equal(x.phase,'playing');assert.equal(x.mustPlayAgain,true);const y=applyAction(x,{type:ACTIONS.END_TURN,playerId:'p0'});assert.equal(y.players[0].hand.length,1)});
test('a final Curse wins immediately without adding or retaining its pending penalty',()=>{for(const players of [2,3,6]){const curse=c(TYPES.PLUS2,'red'),hands=Array.from({length:players},(_,index)=>index?[c(TYPES.NUMBER,'green',4)]:[curse]),s=state({players,hands}),before=hands[1].length,x=play(s,'p0',curse);assert.equal(x.phase,'finished');assert.equal(x.winnerId,'p0');assert.equal(x.players[1].hand.length,before);assert.equal(x.currentPlayerIndex,0);assert.equal(x.activePenalty,null);assert.equal(calculateRoundScore(x),players-1);}});
test('a non-final Curse still stacks and the next player draws the penalty',()=>{const a=c(TYPES.PLUS2,'red'),b=c(TYPES.PLUS2,'blue'),s=state({players:3,hands:[[a,c(TYPES.NUMBER,'red',1)],[b,c(TYPES.NUMBER,'blue',3)],[c(TYPES.NUMBER,'green',4)]]});let x=play(s,'p0',a);x=play(x,'p1',b);assert.equal(x.activePenalty.amount,4);const before=x.players[2].hand.length;x=applyAction(x,{type:ACTIONS.DRAW,playerId:'p2'});assert.equal(x.players[2].hand.length,before+4);assert.equal(x.phase,'playing');assert.equal(x.activePenalty,null)});
test('Change Color waits for and applies choice',()=>{const card=c(TYPES.CHANGE_COLOR),s=state({hands:[[card,c(TYPES.NUMBER,'blue',3)],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',card);assert.ok(x.awaitingColor);x=applyAction(x,{type:ACTIONS.CHOOSE_COLOR,playerId:'p0',color:'green'});assert.equal(x.activeColor,'green');assert.equal(x.currentPlayerIndex,1)});
test('TAKI sequence defers intermediate commands and closes automatically',()=>{const taki=c(TYPES.TAKI,'red'),plus=c(TYPES.PLUS,'red'),num=c(TYPES.NUMBER,'red',7),s=state({hands:[[taki,plus,num,c(TYPES.NUMBER,'blue',9)],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',taki);x=play(x,'p0',plus);x=play(x,'p0',num);assert.equal(x.taki,null);assert.equal(x.mustPlayAgain,false);assert.equal(x.currentPlayerIndex,1);assert.ok(x.log.some(e=>e.type==='takiClosed'))});
test('a different-colored TAKI cannot be played inside an open TAKI',()=>{const redTaki=c(TYPES.TAKI,'red'),blueTaki=c(TYPES.TAKI,'blue'),redCard=c(TYPES.NUMBER,'red',3),s=state({hands:[[redTaki,blueTaki,redCard],[c(TYPES.NUMBER,'red',8)]]});const x=play(s,'p0',redTaki);assert.equal(isLegalPlay(x,'p0',blueTaki.id),false);assert.equal(isLegalPlay(x,'p0',redCard.id),true)});
test('a Crossbow fired with nothing after it stays open for the next player',()=>{const redTaki=c(TYPES.TAKI,'red'),blueCard=c(TYPES.NUMBER,'blue',3),s=state({hands:[[redTaki,blueCard],[c(TYPES.NUMBER,'red',8)]]});const x=play(s,'p0',redTaki);assert.equal(x.currentPlayerIndex,1);assert.equal(x.taki.open,true);assert.equal(x.taki.inherited,true);assert.equal(x.taki.ownerId,'p1');assert.equal(x.taki.color,'red')});
test('player can end an active TAKI and it closes automatically',()=>{const taki=c(TYPES.TAKI,'red'),a=c(TYPES.NUMBER,'red',3),b=c(TYPES.NUMBER,'red',4),s=state({hands:[[taki,a,b],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',taki);x=play(x,'p0',a);x=applyAction(x,{type:ACTIONS.END_TURN,playerId:'p0'});assert.equal(x.taki,null);assert.equal(x.currentPlayerIndex,1)});
test('closing after a Crossbow inside a Crossbow advances in one action',()=>{for(const nestedType of [TYPES.TAKI,TYPES.SUPER_TAKI]){const open=c(TYPES.TAKI,'red'),nested=c(nestedType,nestedType===TYPES.TAKI?'red':'wild'),keep=c(TYPES.NUMBER,'red',3),s=state({hands:[[open,nested,keep],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',open);x=play(x,'p0',nested);assert.ok(x.taki?.open);x=applyAction(x,{type:ACTIONS.END_TURN,playerId:'p0'});assert.equal(x.taki.inherited,true);assert.equal(x.taki.ownerId,'p1');assert.equal(x.currentPlayerIndex,1);assert.equal(x.log.filter(entry=>entry.type==='takiClosed').length,1);}});
test('Runed Crossbow inherits current color in rules and rendering',()=>{const superTaki=c(TYPES.SUPER_TAKI),s=state({hands:[[superTaki,c(TYPES.NUMBER,'red',3)],[c(TYPES.NUMBER,'blue',4)]]});const x=play(s,'p0',superTaki);const played=x.discardPile.at(-1),html=cardHTML(played);assert.equal(x.taki.color,'red');assert.equal(x.activeColor,'red');assert.equal(played.inheritedColor,'red');assert.match(html,/card red type-superTaki inherited/);assert.match(html,/masked-card-asset/);assert.doesNotMatch(html,/native-card-asset|chosen-pip/);assert.match(html,/<span class="card-print">קשת רונית<\/span>/)});
test('colored Crossbow matches a closed Runed Crossbow regardless of color',()=>{const superTaki=c(TYPES.SUPER_TAKI),green=c(TYPES.NUMBER,'green',3),yellowTaki=c(TYPES.TAKI,'yellow'),s=state({hands:[[superTaki,green],[yellowTaki,c(TYPES.NUMBER,'red',4)]],top:c(TYPES.NUMBER,'blue',5),activeColor:'blue'});const x=play(s,'p0',superTaki);assert.equal(x.taki.inherited,true);assert.equal(x.taki.color,'blue');assert.equal(x.currentPlayerIndex,1);assert.equal(x.activeColor,'blue');assert.equal(isLegalPlay(x,'p1',yellowTaki.id),true)});
test('wild artwork stays multicolor until its play color is resolved',()=>{const rune=c(TYPES.CHANGE_COLOR),superTaki=c(TYPES.SUPER_TAKI);assert.match(cardHTML(rune),/native-card-asset/);assert.match(cardHTML(superTaki),/native-card-asset/);const chosen=cardHTML(rune,{activeColor:'blue'});assert.match(chosen,/card blue type-changeColor/);assert.match(chosen,/masked-card-asset/);assert.doesNotMatch(chosen,/native-card-asset|chosen-pip/)});
test('special card labels stay secondary to the supplied artwork',()=>{const shield=cardHTML(c(TYPES.STOP,'red')),curse=cardHTML(c(TYPES.PLUS2,'red')),turnabout=cardHTML(c(TYPES.REVERSE,'blue'));assert.match(shield,/<span class="card-print">מגן<\/span>/);assert.match(shield,/shield\.svg/);assert.doesNotMatch(shield,/corner bottom/);assert.match(curse,/curse-plus-2\.svg/);assert.match(turnabout,/<span class="card-print">שינוי כיוון<\/span>/)});
test('card corners use artwork without a duplicate +2 badge',()=>{const number=cardHTML(c(TYPES.NUMBER,'green',8)),curse=cardHTML(c(TYPES.PLUS2,'blue'));assert.match(number,/corner-asset number-corner-asset/);assert.match(number,/number-8\.svg/);assert.doesNotMatch(number,/corner-value/);assert.match(curse,/corner-asset/);assert.doesNotMatch(curse,/corner-short|>\+2</)});
test('King cancels +2 and creates a free extra turn',()=>{const king=c(TYPES.KING),s=state({hands:[[king,c(TYPES.NUMBER,'blue',3)],[c(TYPES.NUMBER,'blue',4)]]});s.activePenalty={kind:'plus2',amount:6};const x=play(s,'p0',king);assert.equal(x.activePenalty,null);assert.equal(x.freePlay,true);assert.equal(x.currentPlayerIndex,0);assert.equal(getLegalCards(x,'p0').length,1)});
test('King wins normally when played as the final card',()=>{const king=c(TYPES.KING),s=state({hands:[[king],[c(TYPES.NUMBER,'blue',4)]]});s.activePenalty={kind:'plus2',amount:6};const x=play(s,'p0',king);assert.equal(x.phase,'finished');assert.equal(x.winnerId,'p0');assert.equal(x.activePenalty,null);assert.equal(x.mustPlayAgain,false);assert.equal(x.players[0].hand.length,0);assert.equal(x.log.at(-1).type,'win')});
test('Super TAKI after King chooses its own open color',()=>{const king=c(TYPES.KING),superTaki=c(TYPES.SUPER_TAKI),red=c(TYPES.NUMBER,'red',4),s=state({hands:[[king,superTaki,red],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',king);x=play(x,'p0',superTaki);assert.equal(x.awaitingColor.next,'openTaki');x=applyAction(x,{type:ACTIONS.CHOOSE_COLOR,playerId:'p0',color:'red'});assert.equal(x.taki.color,'red');assert.equal(x.activeColor,'red');assert.equal(x.currentPlayerIndex,0);assert.ok(getLegalCards(x,'p0').some(card=>card.id===red.id))});
test('colored TAKI after King stays restricted to its color',()=>{const king=c(TYPES.KING),taki=c(TYPES.TAKI,'yellow'),yellow=c(TYPES.NUMBER,'yellow',3),blueStop=c(TYPES.STOP,'blue'),s=state({hands:[[king,taki,yellow,blueStop],[c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',king);x=play(x,'p0',taki);assert.equal(x.taki.color,'yellow');assert.equal(isLegalPlay(x,'p0',yellow.id),true);assert.equal(isLegalPlay(x,'p0',blueStop.id),false);x=play(x,'p0',yellow);assert.equal(isLegalPlay(x,'p0',blueStop.id),false)});
test('reaching one card needs no announcement or penalty',()=>{const a=c(TYPES.NUMBER,'red',3),b=c(TYPES.NUMBER,'red',4),opp=c(TYPES.NUMBER,'blue',3),s=state({hands:[[a,b],[opp,c(TYPES.NUMBER,'blue',4)]]});let x=play(s,'p0',a),before=x.players[0].hand.length;assert.equal(x.log.some(e=>e.type==='lastCard'),false);x=play(x,'p1',opp);assert.equal(x.players[0].hand.length,before)});
test('restore migrates saved ordinary twos out of every pile and hand',()=>{const s=createInitialState({playerCount:3,seed:77});const legacyTwo={...c(TYPES.NUMBER,'yellow',3),value:2};s.version=4;s.players[0].hand.push(legacyTwo);s.drawPile.push({...c(TYPES.NUMBER,'red',3),value:2});s.discardPile.push({...c(TYPES.NUMBER,'blue',3),value:2});s.effectiveTopIndex=s.discardPile.length-1;const restored=restoreState(serializeState(s));assert.equal(restored.version,6);for(const card of [...restored.drawPile,...restored.discardPile,...restored.players.flatMap(p=>p.hand)])assert.equal(card.type===TYPES.NUMBER&&card.value===2,false)});
test('restore resolves a legacy zero-card Curse candidate as the winner',()=>{const s=state({hands:[[],[c(TYPES.NUMBER,'blue',4)]]});s.version=5;s.candidateWinnerId='p0';const restored=restoreState(serializeState(s));assert.equal(restored.version,6);assert.equal(restored.phase,'finished');assert.equal(restored.winnerId,'p0');assert.equal('candidateWinnerId' in restored,false)});
test('ordinary final card wins',()=>{const card=c(TYPES.NUMBER,'red',3),s=state({hands:[[card],[c(TYPES.NUMBER,'blue',4)]]});const x=play(s,'p0',card);assert.equal(x.phase,'finished');assert.equal(x.winnerId,'p0')});
test('draw pile reshuffles discarded cards without losing the top',()=>{const s=state();s.drawPile=[];s.discardPile=[c(TYPES.NUMBER,'blue',1),c(TYPES.NUMBER,'green',3),c(TYPES.NUMBER,'red',5)];s.effectiveTopIndex=2;const x=applyAction(s,{type:ACTIONS.DRAW,playerId:'p0'});assert.equal(x.players[0].hand.length,2);assert.ok(x.discardPile.some(k=>k.color==='red'))});
test('state serialization restores the exact match',()=>{const s=createInitialState({playerCount:4,seed:99});assert.deepEqual(restoreState(serializeState(s)),s)});
test('Tavern Match initializes exactly four players and five rounds',()=>{const m=createTavernMatch({seed:12});assert.equal(m.mode,'tavern');assert.equal(m.totalRounds,5);assert.equal(m.round,1);assert.equal(m.game.players.length,4);assert.deepEqual(Object.values(m.scores),[0,0,0,0])});
test('round score is the sum of all losing hands',()=>{const m=createTavernMatch({seed:4});m.game.phase='finished';m.game.winnerId='p0';m.game.players.forEach((p,i)=>p.hand=Array(i?i+1:0).fill(c(TYPES.NUMBER,'red',1)));assert.equal(calculateRoundScore(m.game),9);const done=finishRound(m);assert.equal(done.scores.p0,9);assert.equal(done.results[0].points,9)});
test('AI and human winners receive cumulative scores',()=>{let m=createTavernMatch({seed:4});m.game.phase='finished';m.game.winnerId='p1';m.game.players.forEach((p,i)=>p.hand=Array(i===1?0:2).fill(c(TYPES.NUMBER,'red',1)));m=finishRound(m);assert.equal(m.scores.p1,6);m=startNextRound(m);m.game.phase='finished';m.game.winnerId='p0';m.game.players.forEach((p,i)=>p.hand=Array(i?1:0).fill(c(TYPES.NUMBER,'blue',3)));m=finishRound(m);assert.equal(m.scores.p0,3);assert.equal(m.scores.p1,6)});
test('five normal rounds produce final standings',()=>{let m=createTavernMatch({seed:9});for(let round=1;round<=5;round++){m.game.phase='finished';m.game.winnerId='p0';m.game.players.forEach((p,i)=>p.hand=Array(i?1:0).fill(c(TYPES.NUMBER,'red',1)));m=finishRound(m);if(round<5)m=startNextRound(m);}assert.equal(m.phase,'matchFinished');assert.equal(m.championId,'p0');assert.equal(m.results.length,5);assert.equal(standings(m)[0].id,'p0')});
test('tied final standings trigger sudden death and its winner is champion',()=>{let m=createTavernMatch({seed:11});m.round=5;m.scores={p0:10,p1:10,p2:3,p3:2};m.game.phase='finished';m.game.winnerId='p2';m.game.players.forEach(p=>p.hand=[]);m=finishRound(m);assert.equal(m.suddenDeath,true);assert.equal(m.phase,'betweenRounds');m=startNextRound(m);assert.equal(m.round,5);assert.equal(m.game.players.length,4);m.game.phase='finished';m.game.winnerId='p1';m=finishRound(m);assert.equal(m.phase,'matchFinished');assert.equal(m.championId,'p1')});
test('Quick Play is independent from Tavern Match scoring',()=>{const q=createQuickSession({playerCount:2,seed:7});assert.equal(q.game.players.length,2);q.game.phase='finished';q.game.winnerId='p0';const done=finishRound(q);assert.equal(done.phase,'matchFinished');assert.deepEqual(done.scores,{})});
test('Quick Play supports at most five opponents',()=>{const q=createQuickSession({playerCount:10,seed:7});assert.equal(q.game.players.length,6);const oversized={...q,game:createInitialState({playerCount:10,seed:8})};assert.throws(()=>restoreSession(oversized),/Unsupported quick-game player count/);});
test('Tavern Match persists exactly between rounds',()=>{let m=createTavernMatch({seed:42});m.game.phase='finished';m.game.winnerId='p3';m.game.players.forEach((p,i)=>p.hand=Array(i===3?0:i+1).fill(c(TYPES.NUMBER,'green',3)));m=finishRound(m);assert.deepEqual(restoreSession(serializeSession(m)),m)});
test('Tavern Duel uses one human, one fair AI, and five scored rounds',()=>{const opponent=getDuelOpponent('aila'),m=createDuelSession({seed:12,opponent});assert.equal(m.mode,'duel');assert.equal(m.totalRounds,5);assert.equal(m.game.players.length,2);assert.equal(m.game.players[1].duelOpponentId,'aila');assert.equal(m.game.players[1].hand.length,8);assert.equal(m.game.players[0].hand.length,8);assert.equal(DUEL_OPPONENTS.length,15);assert.equal(getDuelOpponent('bramm').aiStyle,'aggressive');assert.equal(getDuelOpponent('veyra').aiStyle,'control');assert.equal(getDuelOpponent('gorvan').aiStyle,'patient')});
test('Duel round score equals only the losing hand',()=>{let m=createDuelSession({seed:4,opponent:getDuelOpponent('bran')});m.game.phase='finished';m.game.winnerId='p0';m.game.players[0].hand=[];m.game.players[1].hand=Array(7).fill(c(TYPES.NUMBER,'red',1));m=finishRound(m);assert.equal(m.scores.p0,7);assert.equal(m.results[0].points,7);m=startNextRound(m);assert.equal(m.game.players.length,2)});
test('Duel always plays five rounds and uses sudden death for a tie',()=>{let m=createDuelSession({seed:9,opponent:getDuelOpponent('ron')});for(let round=1;round<=5;round++){m.game.phase='finished';m.game.winnerId=round%2?'p0':'p1';m.game.players.forEach(p=>p.hand=[]);m=finishRound(m);if(round<5)m=startNextRound(m);}assert.equal(m.phase,'betweenRounds');assert.equal(m.suddenDeath,true);m=startNextRound(m);m.game.phase='finished';m.game.winnerId='p1';m=finishRound(m);assert.equal(m.phase,'matchFinished');assert.equal(m.championId,'p1');assert.equal(m.results.length,6)});

test('a loaded Crossbow cannot be abandoned by drawing; it must be fired',()=>{const taki=c(TYPES.TAKI,'red'),red=c(TYPES.NUMBER,'red',3),s=state({hands:[[taki,red,c(TYPES.NUMBER,'blue',5)],[c(TYPES.NUMBER,'blue',4)]]});const x=play(s,'p0',taki);assert.ok(x.taki?.open);assert.throws(()=>applyAction(x,{type:ACTIONS.DRAW,playerId:'p0'}),/Crossbow/);const fired=applyAction(x,{type:ACTIONS.END_TURN,playerId:'p0'});assert.equal(fired.taki.ownerId,'p1');assert.equal(fired.taki.inherited,true);assert.equal(fired.currentPlayerIndex,1);});
test('each Tavern evening seats three: the nine regulars, and now and then voiced guests (v107: usually all three) — seeded and restorable',()=>{const seen=new Set(),guests={0:0,1:0,2:0,3:0};const regulars=['aila','ron','bran','sela','roderic','lio','mograth','harrow','rusk'],voiced=['bramm','edrin','ragna','kesh','veyra','gorvan'];for(let seed=0;seed<2000;seed++){const m=createTavernMatch({seed});const keys=m.roster.slice(1).map(p=>p.nameKey);assert.equal(m.roster[0].nameKey,'you');assert.equal(new Set(keys).size,3);for(const key of keys){assert.ok(regulars.includes(key)||voiced.includes(key));seen.add(key);}guests[keys.filter(key=>voiced.includes(key)).length]++;assert.deepEqual(createTavernMatch({seed}).roster.map(p=>p.nameKey),m.roster.map(p=>p.nameKey));assert.ok(createTavernMatch({seed,guestMode:'off'}).roster.every(p=>!voiced.includes(p.nameKey)),'the Settings choice "Off" keeps them away');assert.ok(createTavernMatch({seed,voicedGuests:false}).roster.every(p=>!voiced.includes(p.nameKey)));}assert.equal(seen.size,15,'every regular and every voiced guest takes a seat on some evening');assert.ok(guests[3]>guests[2]*2&&guests[2]>guests[1],`a full voiced table over a pair over one alone: ${guests[1]} / ${guests[2]} / ${guests[3]}`);const any=guests[1]+guests[2]+guests[3];assert.ok(any/2000>.3&&any/2000<.4,`guests on about a third of evenings (${any})`);});
test('the opening lead rotates around the table each round and alternates in a Duel',()=>{let m=createTavernMatch({seed:3});assert.equal(m.game.currentPlayerIndex,0);const leaders=[];for(let round=1;round<=4;round++){m.game.phase='finished';m.game.winnerId='p0';m.game.players.forEach((p,i)=>p.hand=i?[c(TYPES.NUMBER,'red',3)]:[]);m=finishRound(m);m=startNextRound(m);leaders.push(m.game.currentPlayerIndex);}assert.deepEqual(leaders,[1,2,3,0]);let d=createDuelSession({seed:5,opponent:getDuelOpponent('ron')});d.game.phase='finished';d.game.winnerId='p1';d.game.players[0].hand=[c(TYPES.NUMBER,'red',3)];d.game.players[1].hand=[];d=startNextRound(finishRound(d));assert.equal(d.game.currentPlayerIndex,1);assert.equal(roundLeader({results:[1,2],roster:[1,2]}),0);});
test('Quick Play opening lead is seeded and always a real seat',()=>{const seen=new Set();for(let seed=1;seed<60;seed++){for(const playerCount of [2,3,4,6]){const q=createQuickSession({playerCount,seed});assert.ok(q.game.currentPlayerIndex>=0&&q.game.currentPlayerIndex<playerCount);seen.add(q.game.currentPlayerIndex);}}assert.ok(seen.size>1);});

test('the second regulars sheet: five men with full sprite sets, restorable names and Hebrew gender',()=>{for(const id of ['roderic','lio','mograth','harrow','rusk']){const o=getDuelOpponent(id);assert.equal(o.id,id);assert.equal(o.sheet,'b');assert.equal(o.gender,'m');for(const state of ['drink','pleased','idle','annoyed','surprised']){assert.equal(o.sprites[state].sheet,'b');assert.ok(o.sprites[state].row>=0&&o.sprites[state].row<5);}for(const pool of ['pleased','annoyed','surprised','drink'])assert.ok(o.dialoguePools[pool].length>=2);const m=createDuelSession({seed:3,opponent:o});assert.equal(m.game.players[1].nameKey,id);}for(const id of ['aila','sela','ron','bran'])assert.equal(getDuelOpponent(id).gender,'f',id);assert.equal(getDuelOpponent('kesh').gender,'m');assert.equal(getDuelOpponent('harrow').archetype,'hunter');});

// Open Crossbow handover
const drawOf=(s,p)=>applyAction(s,{type:ACTIONS.DRAW,playerId:p});
const end=(s,p)=>applyAction(s,{type:ACTIONS.END_TURN,playerId:p});
test('the next player can empty all their cards of an open Crossbow colour',()=>{for(const opener of [c(TYPES.TAKI,'red'),c(TYPES.SUPER_TAKI)]){const r1=c(TYPES.NUMBER,'red',3),r2=c(TYPES.NUMBER,'red',8),r3=c(TYPES.STOP,'red'),s=state({hands:[[opener,c(TYPES.NUMBER,'blue',5)],[r1,r2,r3,c(TYPES.NUMBER,'green',4)],[c(TYPES.NUMBER,'yellow',1)]],players:3});let x=play(s,'p0',opener);assert.ok(x.taki.inherited);assert.equal(x.taki.color,'red');x=play(x,'p1',r1);assert.equal(x.taki.open,true);assert.equal(x.taki.inherited,true);assert.equal(x.taki.ownerId,'p1');x=play(x,'p1',r2);x=play(x,'p1',r3);assert.equal(x.taki,null);assert.equal(x.players[1].hand.length,1);assert.equal(x.currentPlayerIndex,0,'the final Shield skips p2');}});
test('an open Crossbow can be declined by drawing, and does not travel further',()=>{const redTaki=c(TYPES.TAKI,'red'),s=state({hands:[[redTaki,c(TYPES.NUMBER,'blue',5)],[c(TYPES.NUMBER,'red',3)],[c(TYPES.NUMBER,'red',4)]],players:3});let x=play(s,'p0',redTaki);x=drawOf(x,'p1');assert.equal(x.taki,null);assert.equal(x.players[1].hand.length,2);assert.equal(x.currentPlayerIndex,2);x=end(play(s,'p0',redTaki),'p1');assert.equal(x.taki,null,'firing an untouched open Crossbow just draws');assert.equal(x.players[1].hand.length,2);});
test('a player with no matching colour may still answer an open Crossbow normally or draw',()=>{const redTaki=c(TYPES.TAKI,'red'),rune=c(TYPES.CHANGE_COLOR),s=state({hands:[[redTaki,c(TYPES.NUMBER,'blue',5)],[rune,c(TYPES.NUMBER,'blue',3)]]});let x=play(s,'p0',redTaki);assert.deepEqual(getLegalCards(x,'p1').map(card=>card.id),[rune.id]);x=play(x,'p1',rune);assert.equal(x.taki,null);assert.ok(x.awaitingColor);});
test('a Crossbow played as the last card still wins and is not left open',()=>{const redTaki=c(TYPES.TAKI,'red'),s=state({hands:[[redTaki],[c(TYPES.NUMBER,'red',3)]]});const x=play(s,'p0',redTaki);assert.equal(x.phase,'finished');assert.equal(x.winnerId,'p0');assert.equal(x.taki,null);});
test('a Crossbow played with cards after it does not stay open',()=>{const redTaki=c(TYPES.TAKI,'red'),r=c(TYPES.NUMBER,'red',3),s=state({hands:[[redTaki,r,c(TYPES.NUMBER,'blue',5)],[c(TYPES.NUMBER,'red',4)]]});let x=play(s,'p0',redTaki);x=play(x,'p0',r);assert.equal(x.taki,null);assert.equal(x.currentPlayerIndex,1);});

// Final Curse
test('1v1: a final Curse that is returned costs the empty hand 4 cards and play continues',()=>{const a=c(TYPES.PLUS2,'red'),b=c(TYPES.PLUS2,'blue'),s=state({hands:[[a],[b,c(TYPES.NUMBER,'blue',3)]]});let x=play(s,'p0',a);assert.equal(x.phase,'playing');assert.equal(x.currentPlayerIndex,1);assert.deepEqual(x.curseWinners,['p0']);x=play(x,'p1',b);assert.equal(x.phase,'playing');assert.equal(x.currentPlayerIndex,0);assert.equal(x.activePenalty.amount,4);x=drawOf(x,'p0');assert.equal(x.phase,'playing');assert.equal(x.players[0].hand.length,4);assert.equal(x.activePenalty,null);assert.deepEqual(x.curseWinners,[]);assert.equal(x.currentPlayerIndex,1);});
test('1v1: holding a Curse but drawing instead still lets the final Curse win',()=>{const a=c(TYPES.PLUS2,'red'),b=c(TYPES.PLUS2,'blue'),s=state({hands:[[a],[b]]});let x=play(s,'p0',a);x=drawOf(x,'p1');assert.equal(x.phase,'finished');assert.equal(x.winnerId,'p0');});
test('4 players: when everyone returns the Curse the empty hand takes 8',()=>{const curses=[0,1,2,3].map(i=>c(TYPES.PLUS2,COLORS[i])),s=state({players:4,hands:[[curses[0]],[curses[1],c(TYPES.NUMBER,'blue',3)],[curses[2],c(TYPES.NUMBER,'blue',4)],[curses[3],c(TYPES.NUMBER,'blue',5)]]});let x=play(s,'p0',curses[0]);x=play(x,'p1',curses[1]);x=play(x,'p2',curses[2]);x=play(x,'p3',curses[3]);assert.equal(x.phase,'playing');assert.equal(x.currentPlayerIndex,0);x=drawOf(x,'p0');assert.equal(x.players[0].hand.length,8);assert.equal(x.phase,'playing');});
test('4 players: the final Curse wins as soon as the chain reaches someone without a Curse',()=>{const curses=[0,1].map(i=>c(TYPES.PLUS2,COLORS[i])),s=state({players:4,hands:[[curses[0]],[curses[1],c(TYPES.NUMBER,'blue',3)],[c(TYPES.NUMBER,'blue',4)],[c(TYPES.PLUS2,'green'),c(TYPES.NUMBER,'blue',5)]]});let x=play(s,'p0',curses[0]);assert.equal(x.phase,'playing');x=play(x,'p1',curses[1]);assert.equal(x.phase,'finished');assert.equal(x.winnerId,'p0');assert.equal(x.players[2].hand.length,1);});
test('a King that stops the Curse chain also lets the final Curse win',()=>{const a=c(TYPES.PLUS2,'red'),king=c(TYPES.KING),s=state({hands:[[a],[c(TYPES.PLUS2,'blue'),king]]});let x=play(s,'p0',a);x=play(x,'p1',king);assert.equal(x.phase,'finished');assert.equal(x.winnerId,'p0');});
test('a pending final Curse survives save and restore',()=>{const a=c(TYPES.PLUS2,'red'),s=state({hands:[[a],[c(TYPES.PLUS2,'blue'),c(TYPES.NUMBER,'blue',3)]]});const x=restoreState(serializeState(play(s,'p0',a)));assert.deepEqual(x.curseWinners,['p0']);assert.equal(drawOf(x,'p1').winnerId,'p0');});
